ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Runner.entitlements
Due the issue in flutter we need to enable it https://github.com/flutter/flutter/issues/9984
=> Add missing push notification settings

CHANGELOG.md, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/common/firebase/firebase_helper.dart, lib/main.dart, lib/services/auth_service.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
Setting Firebase crashlytics and user id after login.
=> ZOB-29 - Setup firebase crashlytics

CHANGELOG.md, lib/ui/screens/menu_screen.dart, lib/ui/widgets/menu/menu_item.dart
Add visibility property for menu_item widget and hide rate menu item.
Close [ZOB-61 ](https://jira.etnetera.cz/browse/ZOB-61)
=> ZOB-61 Add visibility property for menu_item widget and hide rate menu item

CHANGELOG.md, pubspec.lock, pubspec.yaml
=> Change app version to 0.3.0

CHANGELOG.md, lib/common/constants.dart, lib/ui/screens/boxes_screen.dart, lib/ui/screens/donations_screen.dart, lib/ui/screens/offer_food_screen.dart, lib/ui/screens/order_shipping_of_boxes_screen.dart, lib/ui/screens/overview_screen.dart, lib/ui/widgets/button.dart, lib/ui/widgets/info_banner.dart
https://etnetera.atlassian.net/browse/ZOB-80 
- InfoBanner background color customisation and set to success color
=> ZOB-80 - InfoBanner background color customisation and set to success color

CHANGELOG.md, lib/l10n/app_cs.arb, lib/ui/screens/menu_screen.dart
* This PR updates the toolbar as per https://etnetera.atlassian.net/browse/ZOB-92
=> ZOB-92 - Update toolbar in Profile screen

lib/ui/screens/offer_food_screen.dart, lib/ui/screens/order_shipping_of_boxes_screen.dart, lib/ui/widgets/dialog.dart, lib/ui/widgets/new_offer_floating_button.dart
- JIRA: https://etnetera.atlassian.net/browse/ZOB-97
- The "icon" property has been removed from the dialog widget
=> ZOB-97 - Remove icons from dialog widget

CHANGELOG.md, lib/ui/screens/menu_screen.dart, lib/ui/widgets/menu/menu_user_info.dart
* This PR adds a new item to the profile section as per https://etnetera.atlassian.net/browse/ZOB-91
* Note: Toolbar will be updated in next task https://etnetera.atlassian.net/browse/ZOB-92
=> ZOB-91 - Add user info item | Based on !64

CHANGELOG.md, lib/common/constants.dart
Jira: [ZOB-150](https://etnetera.atlassian.net/browse/ZOB-150)
=> ZOB-150 - Update pickup config time from 35min to 45min

CHANGELOG.md, lib/models/dto/delivery_dto.dart, lib/models/dto/delivery_dto.g.dart, lib/models/dto/meal_dto.dart, lib/models/dto/meal_dto.g.dart, lib/services/delivery_service.dart, lib/services/offered_food_service.dart, lib/ui/widgets/card_list.dart
**Do not merge before #69**
- JIRA: https://etnetera.atlassian.net/browse/ZOB-126
- This MR refactors how data are fetched for cards on dashboard
=> ZOB-126 - Fetch data for dashboard cards | Based on #69

CHANGELOG.md, lib/features/foodboxes/data/mapper/food_box_mapper.dart, lib/features/foodboxes/data/repository/firebase_food_box_repository.dart, lib/features/foodboxes/di/food_box_dependency_container.dart, lib/features/foodboxes/domain/model/box_movement.dart, lib/features/foodboxes/domain/model/box_movement.freezed.dart, lib/features/foodboxes/domain/repository/food_box_repository.dart, lib/features/foodboxes/presentation/screen/box_movement_detail_screen.dart, lib/features/foodboxes/presentation/screen/boxes_screen.dart, lib/features/foodboxes/presentation/widget/box_movement_list.dart, lib/features/foodboxes/presentation/widget/box_movement_list_tile.dart, lib/features/offeredfood/presentation/screens/donations_screen.dart, lib/models/box_movement.dart, lib/models/dto/delivery_dto.dart, lib/models/dto/delivery_dto.g.dart, lib/models/dto/food_box_delivery_dto.dart, lib/models/dto/food_box_delivery_dto.g.dart, lib/routes/app_router.gr.dart, lib/services/box_movement_srvice.dart, lib/ui/screens/home_screen.dart, lib/ui/screens/overview_screen.dart
**Do not merge before https://github.com/zachran-jidlo/zachranobed/pull/74**
- JIRA: https://etnetera.atlassian.net/browse/ZOB-135
- This MR refactors how data for "Krabičky" screen are fetched
[Screen_recording_20240325_210306.webm](https://github.com/zachran-jidlo/zachranobed/assets/80771513/76595f42-50ec-41fc-877d-848d961ccb4c)
=> ZOB-135 - Fetch data for box movements | Based on #74

CHANGELOG.md, lib/common/constants.dart, lib/features/menu/presentation/menu_screen.dart, lib/routes/app_router.gr.dart
Resolves [ZOB-48](https://etnetera.atlassian.net/browse/ZOB-48), [ZOB-53](https://etnetera.atlassian.net/browse/ZOB-53), [ZOB-54](https://etnetera.atlassian.net/browse/ZOB-54)
=> feat - Connected correct links

lib/features/foodboxes/data/repository/firebase_food_box_repository.dart, lib/features/foodboxes/domain/repository/food_box_repository.dart, lib/models/charity.dart, lib/models/dto/delivery_dto.dart, lib/models/dto/delivery_dto.g.dart, lib/models/dto/entity_pair_dto.dart, lib/models/dto/entity_pair_dto.g.dart, lib/services/auth_service.dart, lib/services/delivery_service.dart, lib/ui/screens/order_shipping_of_boxes_screen.dart
* This PR updates delivery food boxes if box delivery exists
* Also changes delivery ID, to not conflict with food delivery
=> Update delivery food boxes

firebase.json, firestore.indexes.json, firestore.rules, functions/README.md
README on how to deploy indexes
Indexes
Rules
Firebase project setup
=> Updated info and data about Firebase project 

CHANGELOG.md, android/app/build.gradle, android/app/src/prod/google-services.json, lib/firebase/firebase_options_prod.dart, pubspec.yaml
* Update application ID
* Update Firebase config
=> ZOB-167 Update Android production application ID

CHANGELOG.md, lib/common/utils/date_time_utils.dart, lib/features/appConfiguration/di/app_configuration_dependency_container.dart, lib/features/foodboxes/presentation/screen/boxes_screen.dart, lib/features/offeredfood/presentation/screens/donations_screen.dart, pubspec.lock
Jira: [ZOB-169](https://etnetera.atlassian.net/browse/ZOB-169)
Add 1 mont history limitation to donations and food boxes.
=> ZOB-169 Limiting the donation and shipping history of a box to 1 month

CHANGELOG.md, lib/firebase/notifications.dart, pubspec.yaml
Jira: [ZOB-155](https://etnetera.atlassian.net/browse/ZOB-155) 
- Correction of notification icon color.
=> ZOB-155 Fix notification icon color for android.

CHANGELOG.md, lib/ui/widgets/donation_countdown_timer.dart
Jira: https://etnetera.atlassian.net/browse/ZOB-122
* Use `Ticker` instead of `Timer`, which should be more precise
* Also invalidate `Ticker` in on-resume callback
=> ZOB-122 Use Ticker for more precision countdown timer

CHANGELOG.md, lib/common/constants.dart, lib/features/foodboxes/presentation/screen/boxes_screen.dart, lib/l10n/app_cs.arb, lib/ui/screens/home_screen.dart, lib/ui/screens/overview_screen.dart
Jira: https://etnetera.atlassian.net/browse/ZOB-96
No FAB + new button for Charity:
No FAB for "Pokrmy" page:
Also I have added a bottom padding so that FAB do not overlap list:
=> ZOB-96 Move FAB to overview screen, add button on empty page

CHANGELOG.md, lib/features/offeredfood/presentation/widget/donated_food_list.dart, lib/ui/screens/overview_screen.dart
Jira: https://etnetera.atlassian.net/browse/ZOB-158
* I have added a new optional param `alwaysShowTitle`, and set it to false on overview screen
* Now it will be hidden when `observeHistory` will return an empty list
=> ZOB-158 Hide list header on overview screen when list is empty

CHANGELOG.md, android/app/build.gradle, android/build.gradle, android/settings.gradle, lib/common/lifecycle/lifecycle_watcher.dart, lib/common/utils/date_time_utils.dart, lib/features/appTerms/domain/update_current_user_data_use_case.dart, lib/features/appTerms/presentation/app_terms_screen.dart, lib/features/login/di/login_dependency_container.dart, lib/features/login/presentation/screen/login_screen.dart, lib/features/offeredfood/data/repository/firebase_offered_food_repository.dart, lib/features/offeredfood/domain/repository/offered_food_repository.dart, lib/models/canteen.dart, lib/notifiers/delivery_notifier.dart, lib/services/delivery_service.dart, lib/ui/screens/home_screen.dart, lib/ui/screens/overview_screen.dart, lib/ui/widgets/app_root.dart, lib/ui/widgets/delivery_info_banner.dart, lib/ui/widgets/donation_countdown_timer.dart, lib/ui/widgets/new_offer_floating_button.dart, pubspec.lock, pubspec.yaml
Jira: https://etnetera.atlassian.net/browse/ZOB-123
- New MR for this JIRA ticket. I canceled the original MR
- Migration after update to last Flutter version 3.22 (https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply) - please run `flutter upgrade --force`
=> ZOB-123 Fix courier arrival banner conditions

CHANGELOG.md, ios/Runner/Info.plist, lib/features/foodboxes/presentation/widget/box_data_table.dart, lib/l10n/app_cs.arb, lib/ui/screens/offer_food_screen.dart, lib/ui/widgets/date_time_picker.dart, lib/ui/widgets/dropdown.dart, lib/ui/widgets/food_section_fields.dart, lib/ui/widgets/form/form_validation_manager.dart, lib/ui/widgets/text_field.dart, pubspec.yaml
Merge `release/1.1.0` into `develop`
=> Merge release/1.1.0 into develop

CHANGELOG.md, lib/features/foodboxes/presentation/widget/box_movement_list.dart, lib/features/foodboxes/presentation/widget/box_movement_list_tile.dart
Jira: https://etnetera.atlassian.net/browse/ZOB-200
* Basically #100, but for another screen.
=> ZOB-200 Fix the issue with wrong layout borders on food boxes list

CHANGELOG.md, lib/features/login/presentation/screen/login_screen.dart, lib/ui/screens/forgot_password_screen.dart, lib/ui/widgets/password_text_field.dart, lib/ui/widgets/text_field.dart
Jira: https://etnetera.atlassian.net/browse/ZOB-101
* We have agreed with Maja to remove auto-correct for login fields. 
* It could be misleading for users if system would try to change their e-mail and / or password.
=> ZOB-101 Disable auto-correct for login fields

CHANGELOG.md, lib/enums/food_form_field_type.dart, lib/l10n/app_cs.arb, lib/ui/widgets/food_alergens_text_field.dart, lib/ui/widgets/food_section_fields.dart
Jira: [ZOB-84](https://etnetera.atlassian.net/browse/ZOB-84)
- New widget `FoodAllergensTextField` for allergen fields that solves the logic of displaying a validation error message and supporting text
https://github.com/zachran-jidlo/zachranobed/assets/55541649/16355891-e0ac-49e3-a9f3-6759450dfda2
=> ZOB-84 Fix display of duplicated messages on allergens field

.github/actions/publish-web/action.yml, .github/workflows/build_web_dev.yml, .github/workflows/build_web_prod.yml, .github/workflows/build_web_stage.yml, lib/common/firebase/firebase_helper.dart, lib/common/logger/zo_logger.dart, lib/firebase/notifications.dart, scripts/start_web_server.sh
* This PR adds GitHub Actions workflows to build and distribute to source repositories built web pages for dev, stage and prod flavors.
* Source repo for dev: https://github.com/zachran-jidlo/zachranobed-web-dev
* Source repo for stage: https://github.com/zachran-jidlo/zachranobed-web-stage
* Source repo for prod: https://github.com/zachran-jidlo/zachranobed-web
* Workflows use common local actions, which can be found in `.github/actions` folder.
* All workflows are designed to trigger one-by-one via [Actions](https://github.com/zachran-jidlo/zachranobed/actions) page.
* Select the needed workflow from the left side, tap on "Run workflow" button to the right and choose a branch to run.
* It is possible to define other triggers (e.g. merge to release branch, or tag creation), this will be …
=> ZOB-202 CI/CD Add dev, stage and prod Web workflows

CHANGELOG.md, ios/Podfile.lock, lib/common/constants.dart, lib/l10n/app_cs.arb, lib/ui/widgets/contact_row.dart, pubspec.lock, pubspec.yaml
* Jira: https://etnetera.atlassian.net/browse/ZOB-218
* Just dummy data on dummy place
* Testing interactions
https://github.com/zachran-jidlo/zachranobed/assets/80771513/d0750539-e49f-4123-945a-15f731c0cac3
=> ZOB-218 Add reusable contact row

CHANGELOG.md, lib/features/menu/presentation/contacts_screen.dart, lib/features/menu/presentation/menu_screen.dart, lib/l10n/app_cs.arb, lib/routes/app_router.dart, lib/routes/app_router.gr.dart, lib/ui/widgets/menu/menu_section.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-225
* New item and screen are added
* Also I have tweaked `MenuSection` text style a bit to match Figma
* And removed invisible "Ohodnotit aplikaci" menu item
=> ZOB-225 Add contacts screen with mocked values

CHANGELOG.md, lib/common/utils/firestore_utils.dart, lib/common/utils/generic_utils.dart, lib/common/utils/iterable_utils.dart, lib/features/menu/data/mapper/contacts_mapper.dart, lib/features/menu/data/repository/firebase_contacts_repository.dart, lib/features/menu/di/menu_dependency_container.dart, lib/features/menu/domain/model/contact.dart, lib/features/menu/domain/model/contact.freezed.dart, lib/features/menu/domain/model/contacts_summary.dart, lib/features/menu/domain/model/contacts_summary.freezed.dart, lib/features/menu/domain/model/entity_contacts.dart, lib/features/menu/domain/model/entity_contacts.freezed.dart, lib/features/menu/domain/repository/contacts_repository.dart, lib/features/menu/domain/usecase/get_contacts_use_case.dart, lib/features/menu/presentation/contacts_screen.dart, lib/l10n/app_cs.arb, lib/main.dart, lib/models/dto/contact_dto.dart, lib/models/dto/contact_dto.g.dart, lib/models/dto/entity_dto.dart, lib/models/dto/entity_dto.g.dart, lib/services/entity_service.dart, lib/services/meal_service.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-223
* Add "target" contacts from firebase
* Carrier and "Zachraň jídlo" contacts will be added in next parts
=> ZOB-223 Use real data for contacts screen - part 1

lib/features/menu/data/repository/firebase_contacts_repository.dart, lib/features/menu/di/menu_dependency_container.dart, lib/models/dto/configuration_contacts_dto.dart, lib/models/dto/configuration_contacts_dto.g.dart, lib/services/configuration_service.dart, lib/services/di/services_dependency_container.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-223
* Add organisation contacts from firebase
* Carrier contacts will be added in next part
=> ZOB-223 Use real data for contacts screen - part 2

lib/features/menu/data/repository/firebase_contacts_repository.dart, lib/features/menu/di/menu_dependency_container.dart, lib/models/dto/carrier_dto.dart, lib/models/dto/carrier_dto.g.dart, lib/services/carrier_service.dart, lib/services/di/services_dependency_container.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-223
* Add carriers contacts from firebase
=> ZOB-223 Use real data for contacts screen - part 3

CHANGELOG.md, lib/common/utils/date_time_utils.dart, lib/features/foodboxes/presentation/screen/boxes_screen.dart, lib/features/offeredfood/presentation/screens/donations_screen.dart
* JIRA:  https://etnetera.atlassian.net/browse/ZOB-170
* Basically reverts changes in 77d99f81.
=> ZOB-170 Remove limit in donation and shipping history

CHANGELOG.md, lib/features/offeredfood/data/repository/firebase_offered_food_repository.dart, lib/features/offeredfood/domain/repository/offered_food_repository.dart, lib/notifiers/delivery_notifier.dart, lib/services/delivery_service.dart, lib/ui/widgets/donation_countdown_timer.dart
* See Slack discussion https://zachraobd.slack.com/archives/C061KTPJTEH/p1721733460811279
* JIRA: https://etnetera.atlassian.net/browse/ZOB-239
=> ZOB-239 Fix NOT_USED state usage

CHANGELOG.md, lib/common/constants.dart, lib/ui/widgets/info_text_banner.dart
Jira: [ZOB-229](https://etnetera.atlassian.net/browse/ZOB-229)
- new widget `InfoTextBanner` for simple text banner
- new color `amberTransparent` for background of banner
=> ZOB-229 Add banner widget with text

CHANGELOG.md, lib/ui/screens/home_screen.dart
Jira: [ZOB-258](https://etnetera.atlassian.net/browse/ZOB-258)
- added button for signOut to home_screen when is loading longer than 20s and user is not loaded
**Demo (time for showing button set to 5s)**
https://github.com/user-attachments/assets/ba1ae191-2607-425b-afe9-40d8a05174d8
=> ZOB-258 Add signOut button to home screen when user is not loaded

CHANGELOG.md, lib/common/constants.dart
Jira: [ZOB-260](https://etnetera.atlassian.net/browse/ZOB-260)
=> ZOB-260 Change app terms link

.github/workflows/build_ios_prod.yml, ios/ExportOptionsProd.plist, ios/Runner.xcodeproj/project.pbxproj
* I have changed it in branch month ago, but forgot to create a PR 🤦‍♂️ 
* Now "Build iOS Prod" should run green
=> ZOB-202 Update iOS prod Provisioning Profile

CHANGELOG.md, lib/common/constants.dart, lib/common/utils/date_time_utils.dart, lib/features/appConfiguration/data/entity/remote_app_configuration_dto.g.dart, lib/features/foodboxes/domain/model/food_box_type.dart, lib/features/offeredfood/domain/model/food_info.dart, lib/features/offeredfood/domain/model/food_info.freezed.dart, lib/l10n/app_cs.arb, lib/models/dto/food_box_delivery_dto.g.dart, lib/models/dto/food_box_pair_dto.g.dart, lib/models/dto/meal_dto.g.dart, lib/routes/app_router.dart, lib/routes/app_router.gr.dart, lib/ui/screens/offer_food_detail_screen.dart, lib/ui/screens/offer_food_overview_screen.dart, lib/ui/screens/offer_food_screen.dart, lib/ui/screens/thank_you_screen.dart, lib/ui/widgets/food_section_fields.dart, lib/ui/widgets/info_text_banner.dart, lib/ui/widgets/trailing_icon_row.dart
**Jira:** [ZOB-231](https://etnetera.atlassian.net/browse/ZOB-231)
- added new screens for overview and editable detail
- updated offer food feature to new flow
**Demo:**
https://github.com/user-attachments/assets/f09636f0-c3eb-4dc7-9dc4-95931fe64182
=> ZOB-231 Add food offer overview screen and feature

CHANGELOG.md, lib/features/offeredfood/data/repository/firebase_offered_food_repository.dart, lib/features/offeredfood/domain/repository/offered_food_repository.dart, lib/notifiers/delivery_notifier.dart, lib/services/delivery_service.dart
* JIRA: https://etnetera.atlassian.net/browse/ZOB-265
* See notes in JIRA to understand why this change is needed.
=> ZOB-265 Change current delivery search conditions

firestore.indexes.json, functions/package-lock.json, functions/package.json, functions/src/index.ts
I've also removed vurnerabilities in Function dependencies.
=> ZOB-33: Notifikování charity v případě, když v jídelně žádné jídlo nezbylo

CHANGELOG.md, lib/features/menu/data/mapper/contacts_mapper.dart, lib/features/menu/data/repository/firebase_contacts_repository.dart, lib/features/menu/domain/model/contact.dart, lib/features/menu/domain/model/contact.freezed.dart, lib/features/menu/presentation/contacts_screen.dart, lib/models/dto/contact_dto.dart, lib/models/dto/contact_dto.g.dart, lib/models/dto/entity_dto.dart, lib/models/dto/entity_dto.g.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-272
* This PR adds optional "position" field for contacts
=> ZOB-272 Add position field to contacts

CHANGELOG.md, lib/ui/widgets/info_text_banner.dart
Jira: https://etnetera.atlassian.net/browse/ZOB-270
=> ZOB-270 Fix food offer overview banner max lines

lib/l10n/app_cs.arb, lib/ui/screens/forgot_password_screen.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-157
* Maja found one "legacy" error message in Forgot Password screen
=> ZOB-157 Change text in snackbar

functions/src/index.ts
* Jira: https://etnetera.atlassian.net/browse/ZOB-283
* Note: In-app copies are updated in #154
=> ZOB-283 Update notifications copy related to shipping boxes from charity

CHANGELOG.md, lib/ui/screens/offer_food_overview_screen.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-284
* This PR adds a scrolling widget for food offer overview screen
=> ZOB-284 Fix scrolling on food offer overview screen

CHANGELOG.md, lib/features/foodboxes/data/repository/firebase_food_box_repository.dart, lib/models/dto/food_box_type_dto.dart, lib/ui/widgets/food_allergens_chips.dart, lib/ui/widgets/food_section_fields.dart, lib/ui/widgets/form_field_error.dart, lib/ui/widgets/single_select_chips.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-298
* Figma: https://www.figma.com/design/j8ffUUxMVaRKjwunypj8GY/zj---Flutter-App?node-id=5430-17025
* This PR updates how user chooses food category and fox type in the food offer form.
* Also extracts form error text to the reusable widget.
=> ZOB-298 Update food categories and box types UI in food offer form

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, android/settings.gradle
* Newer version of Android Studio requires newer Gradle version.
* This should work fine for Stable Android Studio Lady Bug.
=> Update Gradle to 8.9

CHANGELOG.md, lib/common/constants.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-161
=> ZOB-161 Update e-mail address for feedback

CHANGELOG.md, lib/ui/widgets/assist_chip.dart, lib/ui/widgets/form_field_error.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-304
* Figma: https://www.figma.com/design/j8ffUUxMVaRKjwunypj8GY/zj---Flutter-App?node-id=7460-9972&t=u2TLZYXbyxQRJ780-4
=> ZOB-304 Update assist chip and error UI | Merge after #178

CHANGELOG.md, lib/ui/widgets/counter_field.dart
* Jira: https://etnetera.atlassian.net/browse/ZOB-321
* Firebase: https://console.firebase.google.com/project/zachran-obed/crashlytics/app/android:cz.zachranobed/issues/bc364520630fa02c2fb65acbe8ed3d56
* Update may be called in async callback (after focus lost), so has to be checked with "mounted".
* https://github.com/flutter/flutter/issues/134611
=> ZOB-321 Fix exception in counter

CHANGELOG.md, lib/features/foodboxes/presentation/screen/box_movement_detail_screen.dart, lib/features/offeredfood/presentation/screens/donated_food_detail_screen.dart, lib/l10n/app_cs.arb
* Jira: https://go.jira.etnetera.cz/browse/ZOB-209
* Note: We have agreed with Deny to remove time part completely.
=> ZOB-209 Remove time from detail footer

CHANGELOG.md, lib/ui/model/food_allergen.dart, lib/ui/widgets/food_allergens_bottom_sheet.dart, lib/ui/widgets/food_allergens_chips.dart, lib/ui/widgets/food_info_fields.dart, lib/ui/widgets/tooltip.dart
* Jira: https://go.jira.etnetera.cz/browse/ZOB-326
=> ZOB-326 Add a tooltip for allergens

CHANGELOG.md, lib/features/offeredfood/presentation/screens/donated_food_detail_screen.dart, lib/ui/model/food_allergen.dart, lib/ui/widgets/food_allergens_bottom_sheet.dart, lib/ui/widgets/food_allergens_chips.dart, lib/ui/widgets/food_info_fields.dart
* JIRA: https://go.jira.etnetera.cz/browse/ZOB-211
=> ZOB-211 Add allergens info bottom sheet on the detail screen

CHANGELOG.md, lib/features/offeredfood/data/mapper/offered_food_mapper.dart, lib/features/offeredfood/domain/model/offered_food.dart, lib/features/offeredfood/domain/model/offered_food.freezed.dart, lib/features/offeredfood/presentation/screens/donated_food_detail_screen.dart, lib/l10n/app_cs.arb
* JIRA: https://go.jira.etnetera.cz/browse/ZOB-337
=> ZOB-337 Change copy of the packaged food category

.github/workflows/create_report.yml, CHANGELOG.md, cron/scripts/create-delivery-report.js, cron/scripts/package.json
* Jira: https://go.jira.etnetera.cz/browse/ZOB-338
* Add filtering and validation options for delivery reports
* Add new inputs to the `create_report` workflow.
* Implement input validation in `create_report` workflow.
* Modify `create-delivery-report.js` accordingly.
* Also update Firebase version to fix security issue from Dependabot: https://github.com/zachran-jidlo/zachranobed/security/dependabot/15
=> ZOB-338 Add new features to deliveries report

CHANGELOG.md, lib/common/utils/field_validation_utils.dart, lib/common/utils/iterable_utils.dart, lib/enums/food_form_field_type.dart, lib/features/offeredfood/data/mapper/offered_food_mapper.dart, lib/features/offeredfood/data/repository/firebase_offered_food_repository.dart, lib/features/offeredfood/di/offered_food_dependency_container.dart, lib/features/offeredfood/domain/model/food_info.dart, lib/features/offeredfood/domain/model/food_info.freezed.dart, lib/features/offeredfood/domain/model/offered_food.dart, lib/features/offeredfood/domain/model/offered_food.freezed.dart, lib/features/offeredfood/domain/repository/offered_food_repository.dart, lib/features/offeredfood/presentation/screens/donated_food_detail_screen.dart, lib/l10n/app_cs.arb, lib/models/dto/meal_dto.dart, lib/models/dto/meal_dto.g.dart, lib/routes/app_router.dart, lib/routes/app_router.gr.dart, lib/services/delivery_service.dart, lib/ui/model/food_allergen.dart, lib/ui/screens/offer_food_boxes_screen.dart, lib/ui/screens/offer_food_detail_screen.dart, lib/ui/screens/offer_food_overview_screen.dart, lib/ui/screens/order_shipping_of_boxes_screen.dart, lib/ui/widgets/button.dart, lib/ui/widgets/food_allergens_chips.dart, lib/ui/widgets/food_box_counter.dart, lib/ui/widgets/food_info_fields.dart, lib/ui/widgets/food_info_row.dart, lib/ui/widgets/section_header.dart
* Jira: https://go.jira.etnetera.cz/browse/ZOB-340
* Figma: https://www.figma.com/design/j8ffUUxMVaRKjwunypj8GY/ZOB---Flutter-App?node-id=9398-10749
=> ZOB-340 Change offer food flow process

CHANGELOG.md, lib/common/constants.dart, lib/features/foodboxes/data/repository/firebase_food_box_repository.dart, lib/features/offeredfood/data/mapper/delivery_mapper.dart, lib/features/offeredfood/data/repository/firebase_offered_food_repository.dart, lib/models/delivery.dart, lib/models/delivery.freezed.dart, lib/models/dto/delivery_dto.dart, lib/models/dto/delivery_dto.g.dart, lib/models/dto/entity_pair_dto.dart, lib/models/dto/entity_pair_dto.g.dart, lib/models/entity_pair.dart, lib/models/mapper/entity_pair_mapper.dart, lib/routes/app_router.gr.dart, lib/ui/widgets/donation_countdown_timer.dart
* JIRA: https://go.jira.etnetera.cz/browse/ZOB-346
=> ZOB-346 Implement dynamic confirmation time for deliveries

CHANGELOG.md, lib/features/menu/presentation/menu_screen.dart, lib/firebase/notifications.dart, lib/services/auth_service.dart, lib/services/entity_service.dart, lib/ui/screens/change_password_screen.dart, lib/ui/screens/home_screen.dart
* JIRA: https://etnetera.atlassian.net/browse/ZOB-313
* This PR adds a call to remove FCM token from entity on sign out.
=> ZOB-313 Remove FCM token after user signs out

CHANGELOG.md, lib/features/foodboxes/presentation/widget/box_summary.dart, lib/l10n/app_cs.arb, lib/ui/screens/overview_screen.dart, lib/ui/widgets/delivery_info_banner.dart
* JIRA: https://etnetera.atlassian.net/browse/ZOB-350
* Figma: https://www.figma.com/design/j8ffUUxMVaRKjwunypj8GY/ZOB---Flutter-App?node-id=10061-11194
=> ZOB-350 Fix delivery banner logic when food boxes checkup is needed

lib/ui/screens/overview_screen.dart
* JIRA: https://etnetera.atlassian.net/browse/ZOB-350
* This PR adds a scroll to box summary table, as discussed in JIRA & Slack.
=> ZOB-350 Add scroll to box summary on "check" click

functions/.cursor/rules/clean-code.mdc, functions/.cursor/rules/code-quality.mdc, functions/.cursor/rules/project.mdc, functions/.cursor/rules/typescript.mdc, functions/.gitignore, functions/src/index.ts
- Invalid tokens removal
- Notification saving to a entity
- Code cleanup
- Cursor rules addition
=> Implementation of ZOB-341, ZOB-349

CHANGELOG.md, lib/common/firebase/firebase_helper.dart, lib/common/utils/device_utils.dart, lib/common/utils/platform_utils.dart, lib/features/forceupdate/domain/usecase/check_if_upgrade_app_should_be_shown_usecase.dart, lib/firebase/notifications.dart, lib/ui/widgets/adaptive_content.dart, lib/ui/widgets/app_root.dart
* JIRA: https://etnetera.atlassian.net/browse/ZOB-352
* The issue was caused by calling `Platform.operatingSystem` on the web, which throws an exception and interrupts the logout process 🤦 
* As a solution I have introduced `RunningPlatform` class, which checks `kIsWeb` flag before accessing `Platform.operatingSystem`.
=> ZOB-352 Fix logout behavior on Web

CHANGELOG.md, lib/features/foodboxes/data/repository/firebase_food_box_repository.dart, lib/models/dto/delivery_dto.dart, lib/models/dto/delivery_dto.g.dart
* JIRA: https://etnetera.atlassian.net/browse/ZOB-357
* This PR removes `carrierId` from `DeliveryDto` class.
=> ZOB-357 Remove `carrierId` property from delivery DTO
